[build]
  base = "frontend/"
  publish = "dist/"
  command = "npm run build"

[[redirects]]
  from = "/api/*"
  to = "https://api.wyrhtaceramics.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
